### ISSUE TITLE
Solution.

### ISSUE THREAD

**Issue by remoteone1** [agustinruiz/logfix#1]
You may want to try again.  The solution should not be dropping lines that don't start with the process name.

[def  ] ALLOWCERTERRORS      <none>
[def  ] ALLOWIP              <*>
[def  ] ALLOWRENEGOTIATION   <FALSE>
[def  ] AUDITCONSOLE         <*>
[def  ] AUDITDELIMITER       <,>
[def  ] AUDITFILE            <*>

and 

-------------- MAIN STACK --------------
Origin of Main Stack:                   1879048192
Current Main Stack Size:                262144 bytes ( 256 KiB )
Maximum available Main Stack Size:      10485760 bytes ( 10 MiB )
Main Stack Usage:                       2.5%

**Comment by agustinruiz** [comment]
Hi! thanks for checking it.
I added a new analysis that process the two examples provided fine but it will fail with some logs.
I couldn't find a clear pattern that solves all potential logs that i imagine.
¿What do you think?
I will add a new type of analysis that allow the user to select manually what to do for logs that don't meet the pattern.
